import dotenv from "dotenv";
dotenv.config();

export const node = {
    NODE_ENV: "development"
};

export const tokenSet = {
    TOKEN_EXPIRE_TIME: 259200, //Three day
    REFRSHTOKEN_EXPIRE_TIME: 604800,
    JWT_SECRET_KEY: process.env.JWT_SECRET_KEY,
    JWT_REFRSHTOKEN_SECRET_KEY: process.env.JWT_REFRSHTOKEN_SECRET_KEY,
    SECRET_KEY: process.env.SECRET_KEY
};

export const role = {
    ADMIN_ROLE: "ADMIN",
    STAFF_ROLE: "STAFF",
    CUSTOMER_ROLE: "CUSTOMER"
};

export const statusMessage = {
    UNAUTHORIZED:"UNAUTHORIZED",
    TOKEN_IS_NOT_VALID: "TOKEN_IS_NOT_VALID",
    ADMIN_ROLE: "ADMIN_ROLE",
    PERMISSION_DENIED: "PERMISSION_DENIED",
    BAD_REQUEST: "BAD_REQUEST",
    USER_NOT_FOUND: "USER_NOT_FOUND",
    USER_ALREADY_EXIST: "USER_ALREADY_EXIST",
    PASSWORD_NOT_MATCH: "PASSWORD_NOT_MATCH",
    TOKEN_IS_EXPIRED: "TOKEN_IS_EXPIRED",
    CREATE_SUCCESS: "CREATE_SUCCESS",
    SUCCESS: "SUCCESS",
    UPDATE_SUCCESS: "UPDATE_SUCCESS",
    DELETE_SUCCESS: "DELETE_SUCCESS",
    GET_SUCCESS: "GET_SUCCESS",
    SERVER_ERROR: "SERVER_ERROR",
    PERMISSION_DENIED: "PERMISSION_DENIED",
    THREATENEDSPECIES_NOT_FOUND: "THREATENEDSPECIES_NOT_FOUND",
    REQUEST_TOKEN:"REQUEST_TOKEN",
    PATROLLING_NOT_FOUND:"PATROLLING_NOT_FOUND",
    INVALID_PARAMS: "INVALID_PARAMS: ",
}